// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2IcUw4_l4HB80Axfuvuo2HZBj_yn2KiU',
    appId: '1:870463690184:web:f24ae2f2b95298b3ce5cfd',
    messagingSenderId: '870463690184',
    projectId: 'flutter-study-2nd-nomad',
    authDomain: 'flutter-study-2nd-nomad.firebaseapp.com',
    storageBucket: 'flutter-study-2nd-nomad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo_mDOXgfJvJ2DUaFi8ON3BOvL_syLMcg',
    appId: '1:870463690184:android:7a0bb1965f406224ce5cfd',
    messagingSenderId: '870463690184',
    projectId: 'flutter-study-2nd-nomad',
    storageBucket: 'flutter-study-2nd-nomad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAic6gaePvzRRh4Fvp33MKyLzYfvH6JRuk',
    appId: '1:870463690184:ios:13019c521929903bce5cfd',
    messagingSenderId: '870463690184',
    projectId: 'flutter-study-2nd-nomad',
    storageBucket: 'flutter-study-2nd-nomad.appspot.com',
    iosBundleId: 'com.example.study2ndProject',
  );
}
